"""
schemas.py — Pydantic models for request/response validation.

These schemas define the shape of data flowing through the API,
ensuring type safety and automatic documentation in Swagger.
"""

from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime


# =============================================================================
# Ingredient & Macro Models (returned by AI analysis)
# =============================================================================

class Ingredient(BaseModel):
    """A single ingredient identified by AI from the food image."""
    name: str = Field(..., description="Name of the ingredient (e.g., 'grilled chicken breast')")
    estimated_grams: float = Field(..., description="Estimated weight in grams")
    confidence: Optional[str] = Field(None, description="AI confidence level: high, medium, low")
    # Added macro fields per ingredient
    calories: float = Field(0, description="Calories in kcal")
    protein_g: float = Field(0, description="Protein in grams")
    carbs_g: float = Field(0, description="Carbs in grams")
    fats_g: float = Field(0, description="Fats in grams")


class MacroBreakdown(BaseModel):
    """Nutritional macro breakdown for a meal or ingredient."""
    calories: float = Field(0, description="Total kilocalories")
    protein_g: float = Field(0, description="Protein in grams")
    carbs_g: float = Field(0, description="Carbohydrates in grams")
    fats_g: float = Field(0, description="Total fats in grams")


# =============================================================================
# Analyze Meal Response
# =============================================================================

class AnalyzeMealResponse(BaseModel):
    """
    The unified response returned after analyzing a food photo.
    Includes the AI-identified ingredients and the calculated macros.
    """
    ingredients: List[Ingredient] = Field(default_factory=list)
    totals: MacroBreakdown = Field(default_factory=MacroBreakdown)
    meal_name: Optional[str] = Field(None, description="Descriptive name for the meal generated by AI")
    ai_notes: Optional[str] = Field(None, description="Any additional notes from the AI (e.g., 'Cooking oil estimated at 1 tbsp')")


# =============================================================================
# Log Meal Request & Response
# =============================================================================

class LogMealRequest(BaseModel):
    """Payload sent by the frontend to save a meal to the database."""
    meal_name: str = Field("Unnamed Meal", description="User-defined name for the meal (e.g., 'Lunch')")
    ingredients: List[Ingredient]
    totals: MacroBreakdown
    ai_notes: Optional[str] = None
    image_base64: Optional[str] = Field(None, description="Optional base64 thumbnail for the meal log")
    logged_at: Optional[str] = Field(None, description="Optional ISO timestamp for the meal log")


class RefineMealRequest(BaseModel):
    """Payload to refine an AI analysis using natural language feedback."""
    ingredients: List[Ingredient]
    feedback: str = Field(..., description="The natural language feedback from the user.")


class UpdateMealRequest(BaseModel):
    """Payload sent by the frontend to update an existing meal."""
    meal_name: Optional[str] = None
    calories: Optional[float] = None
    protein_g: Optional[float] = None
    carbs_g: Optional[float] = None
    fats_g: Optional[float] = None
    ingredients: Optional[List[Ingredient]] = None
    ai_notes: Optional[str] = None


class LogMealResponse(BaseModel):
    """Confirmation returned after successfully logging a meal."""
    success: bool
    meal_id: str
    message: str


# =============================================================================
# Daily Summary Response
# =============================================================================

class MealSummaryItem(BaseModel):
    """A single meal entry within the daily summary (lightweight)."""
    id: str
    meal_name: str
    logged_at: str
    calories: float
    protein_g: float
    carbs_g: float
    fats_g: float


class MealDetailResponse(BaseModel):
    """Full detail for a single meal log, including ingredients and notes."""
    id: str
    meal_name: str
    logged_at: str
    calories: float
    protein_g: float
    carbs_g: float
    fats_g: float
    ingredients: List[Ingredient]
    ai_notes: Optional[str] = None
    image_base64: Optional[str] = None


class DailySummaryResponse(BaseModel):
    """
    Aggregated nutritional data for all meals logged on a specific date.
    Includes grand totals and the individual meal breakdown.
    """
    date: str
    total_calories: float = 0
    total_protein_g: float = 0
    total_carbs_g: float = 0
    total_fats_g: float = 0
    meal_count: int = 0
    meals: List[MealSummaryItem] = Field(default_factory=list)


# =============================================================================
# User Settings (Calorie Goal)
# =============================================================================

class UserSettings(BaseModel):
    """User-configurable settings, primarily the daily calorie goal."""
    daily_calorie_goal: float = Field(2000, description="The user's daily calorie target in kcal")
    language: str = Field("es", description="Language preference (en or es)")


class UserSettingsResponse(BaseModel):
    """Response after fetching or updating user settings."""
    daily_calorie_goal: float
    language: str = "es"
    message: Optional[str] = None


# =============================================================================
# Manual Meal Entry (no image required)
# =============================================================================

class ManualLogMealRequest(BaseModel):
    """Payload for manually logging a meal without AI analysis."""
    meal_name: str = Field("Unnamed Meal", description="Name for the meal")
    calories: float = Field(0, description="Estimated calories")
    protein_g: float = Field(0, description="Protein in grams (optional)")
    carbs_g: float = Field(0, description="Carbs in grams (optional)")
    fats_g: float = Field(0, description="Fats in grams (optional)")
    logged_at: Optional[str] = Field(None, description="Optional ISO timestamp for the meal log")


# =============================================================================
# Trends Data
# =============================================================================

class TrendsDayData(BaseModel):
    """A single day's aggregated data for the trends chart."""
    date: str
    total_calories: float = 0
    total_protein_g: float = 0
    total_carbs_g: float = 0
    total_fats_g: float = 0
    meal_count: int = 0


class TrendsResponse(BaseModel):
    """Aggregated trends data over a date range."""
    days: List[TrendsDayData] = Field(default_factory=list)
    daily_average_calories: float = 0
    total_meals: int = 0
    total_protein_g: float = 0
    total_carbs_g: float = 0
    total_fats_g: float = 0
    goal_hit_days: int = Field(0, description="Number of days where calories were at or below goal")
